# 토큰의 암호화 코드 (테스트용 키) fdsf
jwt:
  secret: hellochoonsikworldmynameischoonsikwemustlovethechoonsik

cloud:
  aws:
    s3:
      bucket: chat-pt
    credentials:
      access-key: AKIAZI2LFC55BJCZ4XUI
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false